version: "3.8"
services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./init/nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TIMEZONE: "Asia/Bangkok"
    ports:
      - "5000:5000"
    volumes:
      - "./:/var/www/"
      - "/var/www/tmp"
    command: 'sh -c "cd /var/www/ && air"'
  redis:
    image: redis:6.0.10-alpine
    volumes:
      - "./init/database/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TIMEZONE: "Asia/Bangkok"
    volumes:
      - ./init/database/mysql/:/docker-entrypoint-initdb.d/
      