upstream go_upstream {
    server host.docker.internal:5000;
    keepalive 64;
}
server {
    listen 80;
    server_name mydevelopment.local;
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_max_temp_file_size 0;
        proxy_pass http://go_upstream;
        proxy_redirect off;
        proxy_read_timeout 240s;
    }
}